spring.application.name=securitydemo
server.port=8082

# Default Spring Security user
spring.security.user.name=admin
spring.security.user.password=demo@123

# H2 Database
spring.datasource.url=jdbc:h2:mem:test
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.app.jwtSecret=VGhpc0lzQVNlY3JldEtleUZvckpXVFRva2VuU2lnbmluZw==
spring.app.jwtExpirationMs=30000

spring.sql.init.mode=always
